#FROM registry.access.redhat.com/rhel7/rhel-atomic
FROM registry.access.redhat.com/rhel-atomic
MAINTAINER Sematext Group Inc. <redhat@sematext.com>
### Atomic/OpenShift Labels - https://github.com/projectatomic/ContainerApplicationGenericLabels
LABEL name="sematext/sematext-agent-docker" \
      vendor="Sematext Group Inc." \
      version="1.31.31" \
      release="1" \
      summary="Sematext Docker Agent" \
      description="Sematext Agent is a modern, open-source, container-native monitoring and log collection agent for Docker. It runs as a tiny container on every Docker host and provides automatic collection and processing of Docker Metrics, Events and Logs for all cluster nodes and all auto-discovered containers. It works with Open Shift/Kubernetes or any other platform supporting Docker containers." \
### Required labels above - recommended below
      url="https://sematext.com/docker" \
      run='docker run --privileged --name ${NAME} -e LOGSENE_TOKEN=${LOGSENE_TOKEN} -e ${SPM_TOKEN} -v /var/run/docker.sock:/var/run/docker.sock ${IMAGE}' \
      io.k8s.description="Sematext Docker Agent collects metrics, docker events and container logs" \
      io.k8s.display-name="Sematext Docker Agent" \
      io.openshift.tags="sematext,monitoring,logging"

RUN mkdir /licenses
COPY ./LICENSE /licenses/LICENSE
COPY README.md /tmp/help.md

WORKDIR /usr/src/app
# Setup Node.js 
RUN microdnf install  gcc-c++ make git --enablerepo=rhel-7-server-rpms && microdnf clean all
# --enablerepo=rhel-7-server-optional-rpms 
RUN curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
RUN microdnf install -y nodejs
COPY . /usr/src/app
RUN npm install -g 
RUN ln -s /usr/src/app/run.sh /usr/local/bin/run-sematext-agent
# Setup tini https://github.com/krallin/tini
ENV TINI_VERSION v0.15.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /sbin/tini
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini.asc /sbin/tini.asc
# ha.pool.sks-keyservers.net not reachable at build time
# RUN gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7 && gpg --verify /sbin/tini.asc 
RUN chmod +x /sbin/tini
RUN microdnf clean all
EXPOSE 9000

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["run-sematext-agent"]

